# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 564b8ae740a5f71a56b3cc07e7b2f71fa7718cba9101f2ecd2e39488f3121c5bd5e90030f89062cf9b55c77323d305ea7d3aab303c806838f82be36880f49a12

test:
  secret_key_base: 06beee80dfb7b2972853b9810a2b21c73089c079f21c7ad4f99b1780212aecbc31b2d1a05cec4d9a15f6cab76e8b0e2e0c1f7889f2aedd8d4e2f7b74b718b69b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
